### ISSUE TITLE
Gossip button height is wrong when adding number causes wrap

### ISSUE THREAD

**Issue by mbattersby** [N0ich/dialogkey-DF#18]
![image](https://user-images.githubusercontent.com/1300207/205469939-5ce86194-8f2e-4fb1-a798-68e91e342d8a.png)

I think a better way of doing this is probably to hack the scrollbox dataprovider, rather than SetText, and let Blizzard do all the layout.

E.g.,

```lua
local function ReplaceProvider(frame)
   local i = 1
   
   local dp = frame.GreetingPanel.ScrollBox:GetDataProvider()
   
   for _, item in ipairs(dp.collection) do
      if item.buttonType == GOSSIP_BUTTON_TYPE_OPTION then
         item.info.name = i .. " " .. item.info.name
         i = i + 1
      elseif item.buttonType == GOSSIP_BUTTON_TYPE_ACTIVE_QUEST or
             item.buttonType == GOSSIP_BUTTON_TYPE_AVAILABLE_QUEST then
         item.info.title = i .. " " .. item.info.title
         i = i + 1
      end
   end
   
   frame.GreetingPanel.ScrollBox:SetDataProvider(dp)
end

hooksecurefunc(GossipFrame, 'Update', ReplaceProvider)
```

**Comment by FuriousProgrammer** [comment]
Unfortunately, while this is a very clean solution, there is no equivalent DataProvider for QuestFrame stuff, only for GossipFrame stuff.

Luckily, there was a fix in the original DialogKey that we overlooked when making the current `SetText()` code!

**Comment by FuriousProgrammer** [comment]
Nevermind, that fix only works for QuestGreetingFrame *grumble grumble*.

**Comment by mbattersby** [comment]
What is the fix? I made (prior to your comment) a version that used DataProvider for the GossipFrame and left QuestFrame different:

https://github.com/xod-wow/dialogkey-DF/tree/updates

Perhaps we can combine?

**Comment by FuriousProgrammer** [comment]
QuestFrame uses a TitleFramePool for the buttons, a consequence of which is that the buttons are anchored to each other like a ladder. The fix for the overlapping text there is to just increase the actual height of the button, which you can see done at the bottom of the current code's EnumerateGossips function.

As I type this I've got a slightly modified version of your DataProvider hook (which is *way* cleaner than the DataProvider hack @N0ich had in the code before, which we inherited from the original addon) in my local dev code that I'm gonna push in a moment.

**Comment by mbattersby** [comment]
I think it may need some kind of already-enumerated flag. I suspect it's possible in rare circumstances for it to double-number (or I guess in theory more).

**Comment by mbattersby** [comment]
Appreciate your fixing this

**Comment by N0ich** [comment]
This is great, thank you
