### ISSUE TITLE
Disable space bar in ghost form after death

### ISSUE THREAD

**Issue by ghost** [N0ich/dialogkey-DF#29]
Hello,

A huge annoyance is addon interaction with resurrection button in ghost form.
Example:
1. Die
2. In spirit form, try to fly up on your drake / jump up
3. As you can see, the 'cancel' button is pressed each time!!! instead of jumping/flying up
![image](https://github.com/N0ich/dialogkey-DF/assets/122007087/1d29f0f9-3819-4e20-aaa7-b8a091f4a5ac)

Please find a way to solve this or disable this key when in ghost form as there is no reason for it imo

Thank you

**Comment by FuriousProgrammer** [comment]
So this isn't actually a bug, as such. DialogKey is *correctly* attempting to hit that button, but you don't *want* it to because you have Spacebar bound to jump/fly up.

I'd recommend changing the DialogKey keybind, personally, but another option is the custom blacklist. The in-game options for it aren't implemented yet (working on this Soon:tm:!) but the addon does currently work with it, you just need to add the `dialogBlacklist` Table to your `WTF\Account\[AccountNumber]\SavedVariables\DialogKey.lua` file, like this:

```lua
DialogKeyDFDB = {
	["global"] = {
		["dialogBlacklist"] = {
			"Resurrection in",
			"Another Example",
			"THE TURTLES MADE IT TO THE WATER",
		},
	},
}
```

Until I get the in-game options for this working, I'll keep the "Resurrection in" string in the built-in blacklist, at which point I'll move it to the custom blacklist as an example default option, as I agree this one should probably never be used!

**Comment by Rezy942** [comment]
Whatever change happened months ago actually fixed the issue.
I cant see anyone actually wanting to press resurrect button in ghost form. It just invites accidents. Youre not saving any time.
Personally resurrect should stay out of buttons that the addon controls.
Sorry im not a dev if this doesnt make sense.

**Comment by FuriousProgrammer** [comment]
So that *specific* dialog (cancelling a BG resurrection timer) is one that
sensible to be disabled, but there is no issue with the addon actually
clicking, so I'm against completely disabling it in favor of making it a
default option in the custom blacklist, as I said.

Personally, one of my main uses for this addon is accepting combat rezzes
and releases, but I understand that some people explicitly don't want that,
which is why there are options for it!
