### ISSUE TITLE
WOTLK Release

### ISSUE THREAD

**Issue by mathwro** [N0ich/dialogkey-DF#33]
Hey. Love the addon and have been using it a while on classic wotlk where it works great as well.

I was hoping you release the addon for WOTLK as well to enable auto updating?

Thanks!

**Comment by FuriousProgrammer** [comment]
We currently don't have plans for maintaining this for any Classic version
of WoW, which is why we don't have a Wrath-compatible TOC file right now,
but this decision was made back when Wrath Classic was using the Legion
client.

IIRC, Wrath Classic uses the DF client now, and as you say this version of
the addon apparently works just fine there. Are there any bugs or Lua
errors *at all* when using DialogKey on Wrath Classic? If I don't have to
do any major work to keep the addon working in both versions I'd be happy
to add the Wrath TOC file to the next release!

**Comment by mathwro** [comment]
The only bugs and Lua errors I've experienced have been when I have been running an older release (hence me asking for the wotlk release). Besides that I have been a happy user for just over half a year without issues
